name: Assign current PRs or Issue to Github Project

on:
  workflow_call:
    secrets:
      MY_GITHUB_TOKEN:
        required: true

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign to the one and only Project
    steps:
      - name: Assign new issues and new pull requests to project
        uses: srggrs/assign-one-project-github-action@1.2.1
        with:
          project: 'https://github.com/orgs/lawpilots/projects/3'
          column_name: 'To do'
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
