name: Auto-assign PRs and Issues to Github Project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]

jobs:
  assign_to_project:
    uses: lawpilots/actions/.github/workflows/assign_to_project.yml@main
    with:
      project: https://github.com/orgs/lawpilots/projects/3
